stages:
  - build
  - merge

variables:
  IMAGE: brighterly/ssh-client

default:
  image: docker:26
  services:
    - docker:26
  before_script:
    - docker info
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

#
# Build stage
#

.build:
  stage: build
  script:
    - docker build --platform $PLATFORM -t $IMAGE:$TAG .
    - docker push $IMAGE:$TAG

build-amd:
  extends: .build
  variables:
    TAG: latest-amd64
    PLATFORM: linux/amd64

build-arm:
  extends: .build
  variables:
    TAG: latest-arm64
    PLATFORM: linux/arm64
  tags:
    - saas-linux-small-arm64

#
# Merge stage
#

manifest:
  stage: merge
  script:
    - docker manifest create $IMAGE:latest
      --amend $IMAGE:latest-amd64
      --amend $IMAGE:latest-arm64
    - docker manifest push $IMAGE:latest
  only:
    - main
